import { AIChatMessage } from '../types';

export async function sendAIChatQuery(message: string, history: AIChatMessage[]) {
  try {
    const res = await fetch('/api/ai/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ message, history }),
    });

    if (!res.ok) {
      throw new Error(`Server returned status ${res.status}`);
    }

    const data = await res.json();
    return data;
  } catch (err) {
    console.warn("Server API call failed, providing offline client fallback:", err);
    return {
      reply: `**Scripture Focus:** *Romans 8:28*\n\n"And we know that in all things God works for the good of those who love him, who have been called according to his purpose."\n\nThank you for asking about: "${message}". God's Word is a lamp unto our feet. Remember to read the surrounding chapter context in the Bible tab for deeper revelation!`,
      scriptureReferences: ["Romans 8:28", "Psalm 119:105"]
    };
  }
}

export async function generateCustomDevotional(topic: string, mood?: string) {
  try {
    const res = await fetch('/api/ai/devotional', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ topic, userMood: mood }),
    });
    if (!res.ok) throw new Error('Devotional generation error');
    return await res.json();
  } catch (err) {
    return {
      title: `Finding God's Peace in ${topic || 'Daily Life'}`,
      scripture: 'Proverbs 3:5-6',
      verseText: 'Trust in the LORD with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.',
      devotional: 'When faced with choices and feelings of anxiety or uncertainty, God invites us to step into faith rather than self-reliance.',
      reflectionQuestion: 'How can you give this situation to God today?',
      prayer: 'Lord Jesus, I surrender my path to You and place my total trust in Your divine love. Amen.'
    };
  }
}

export async function generateAIStudyPlan(goal: string, durationDays: number = 7) {
  try {
    const res = await fetch('/api/ai/study-plan', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ goal, durationDays }),
    });
    if (!res.ok) throw new Error('Study plan error');
    return await res.json();
  } catch (err) {
    return {
      title: `${goal} - 7 Day Bible Journey`,
      description: 'A customized 7-day Bible study plan generated by FaithPath AI to deepen your spiritual walk.',
      days: Array.from({ length: durationDays }, (_, i) => ({
        day: i + 1,
        title: `Day ${i + 1}: Step of Faith`,
        passage: i % 2 === 0 ? 'Psalm 23:1-6' : 'Romans 8:28-39',
        summary: `Reflect on God's promises and practice daily surrender.`
      }))
    };
  }
}

export async function summarizeSermonNotes(notes: string) {
  try {
    const res = await fetch('/api/ai/sermon-summary', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ notes }),
    });
    if (!res.ok) throw new Error('Sermon summary error');
    return await res.json();
  } catch (err) {
    return {
      title: 'Sermon Summary',
      mainTheme: 'Living an Overcoming Faith',
      keyVerses: ['Philippians 4:13', 'Hebrews 11:1'],
      keyTakeaways: [
        'Faith is active trust in God during quiet and storm alike.',
        'Prayer aligns our desires with God\'s heart.',
        'Encouraging others strengthens our own faith walk.'
      ],
      applicationStep: 'Write down 3 blessings this week and thank God for them in prayer.'
    };
  }
}
